In [1]:
a=2
print(a)

2


In [3]:
import numpy as np


In [4]:
list=[1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
arr=np.random.rand(3,4)
arr

array([[0.22403097, 0.23010324, 0.70520762, 0.40226069],
       [0.55593615, 0.03749887, 0.39424325, 0.5706298 ],
       [0.46260926, 0.43788128, 0.97684984, 0.60140912]])

In [12]:
arr=np.random.randint(1,101,(5,5))
arr

array([[ 8, 86, 28, 86, 73],
       [ 8, 98, 57, 84, 22],
       [98, 10,  9, 72, 62],
       [61, 34, 82, 96, 57],
       [75, 48, 17, 38, 86]], dtype=int32)

In [13]:
arr=np.arange(25).reshape(5,5)
arr.shape

(5, 5)

In [14]:
arr.dtype

dtype('int64')

In [15]:
arr.size

25

In [16]:
arr=np.array([1,2,3],dtype=float)
arr

array([1., 2., 3.])

In [17]:
arr.dtype

dtype('float64')

In [18]:
arr.astype(int)

array([1, 2, 3])

In [19]:
#indexing & slicing

In [20]:
arr1=np.arange(10)
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr1[0]

np.int64(0)

In [23]:
arr1[9]

np.int64(9)

In [24]:
#18
arr1[2:6]

array([2, 3, 4, 5])

In [25]:
#19
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
#20
arr2[1,2]

np.int64(6)

In [27]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
#21
arr2[0,:]

array([1, 2, 3])

In [29]:
#22
arr2[:,1]

array([2, 5, 8])

In [30]:
#23
arr2[:2,:2]

array([[1, 2],
       [4, 5]])

In [31]:
#24 
a=arr1>5
a

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [32]:
#25
arr1[a]

array([6, 7, 8, 9])

In [33]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
#26
odd=arr2[arr2%2==1]
odd


array([1, 3, 5, 7, 9])

In [35]:
#27
replace=arr1[arr1>5]=0
replace

0

In [36]:
arr1

array([0, 1, 2, 3, 4, 5, 0, 0, 0, 0])

In [37]:
#28
arr1[[1,3,7]]

array([1, 3, 0])

In [38]:
#29
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr2[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [40]:
#30
arr1

array([0, 1, 2, 3, 4, 5, 0, 0, 0, 0])

In [41]:
#31 #copy 
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a=arr2.copy()
a[0,2]=2
a


array([[1, 2, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
#32
dig=np.diag(arr2)
dig

array([1, 5, 9])

In [55]:
#33
arr2[arr2[:,0]<5]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
#34
arr2[[0,1,2],[1,0,2]]

array([2, 4, 9])

In [57]:
#35
arr2[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [63]:
#Part 3: Mathematical & Universal Functions (UFuncs) 
import numpy as np

In [91]:
a = np.array([1, 2, 3, 4]) 
b = np.array([5, 6, 7, 8]) 

In [92]:
#36
a + b


array([ 6,  8, 10, 12])

In [93]:
#37
a * 3

array([ 3,  6,  9, 12])

In [94]:
#38
a ** 2

array([ 1,  4,  9, 16])

In [95]:
#39
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [96]:
#40
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [97]:
#41
np.sum(a)

np.int64(10)

In [98]:
#42
np.mean(b)

np.float64(6.5)

In [99]:
#43
np.max(a)

np.int64(4)

In [100]:
#44
np.min(b)

np.int64(5)

In [101]:
#45
a1=np.arange(12).reshape(3,4)
np.sum(a)

np.int64(10)

In [102]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
#46
np.sum(a1,axis=0)

array([12, 15, 18, 21])

In [104]:
#47
np.mean(a1,axis=1)

array([1.5, 5.5, 9.5])

In [105]:
#48
np.min(a1,axis=1)

array([0, 4, 8])

In [107]:
#49
np.maximum(a,b)

array([5, 6, 7, 8])

In [108]:
#50
arr=np.array([1.5,2.3,3.8])
np.round(arr)

array([2., 2., 4.])

In [109]:
#51
np.std(a)

np.float64(1.118033988749895)

In [110]:
#52
np.cumsum(a)

array([ 1,  3,  6, 10])

In [111]:
#53
a==b

array([False, False, False, False])

In [116]:
#54
a
np.any(a>2)

np.True_

In [118]:
#55
np.all(b>4)

np.True_

In [170]:
#KEY MANIPULATION TECHNIQUE
import numpy as np

In [171]:
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [172]:
#57
arr=np.array([[1,2],[3,4]])
np.ravel(arr)

array([1, 2, 3, 4])

In [173]:
#58
arr

array([[1, 2],
       [3, 4]])

In [174]:
#59
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [175]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [178]:
a=np.ones((2,3))
b=np.zeros((2,3))
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [179]:
#61
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [180]:
#62
np.concatenate((a,b),axis=0)

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [184]:
#63
arr=np.arange(10)
np.split(arr,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [189]:
#64
arr=np.arange(16).reshape(4,4)
np.hsplit(arr,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [190]:
#65
arr=np.array([1,2,3,4])
np.insert(arr,2,88)

array([ 1,  2, 88,  3,  4])

In [191]:
#66
np.append(arr,5)

array([1, 2, 3, 4, 5])