In [1]:
a=2
print(a)

2


In [1]:
import numpy as np


In [4]:
list=[1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
arr=np.random.rand(3,4)
arr

array([[0.50196672, 0.95553561, 0.137863  , 0.96990026],
       [0.64327595, 0.99284748, 0.2429922 , 0.7120749 ],
       [0.46913566, 0.09406491, 0.82579377, 0.36319579]])

In [30]:
arr=np.random.randint(1,101,(5,5))
arr

array([[ 8, 61, 71, 19, 27],
       [91, 16, 77, 74, 23],
       [30, 95, 62,  7,  3],
       [50, 11, 35, 99, 31],
       [15, 31, 55, 28, 95]], dtype=int32)

In [32]:
arr=np.arange(25).reshape(5,5)
arr.shape

(5, 5)

In [33]:
arr.dtype

dtype('int64')

In [34]:
arr.size

25

In [37]:
arr=np.array([1,2,3],dtype=float)
arr

array([1., 2., 3.])

In [38]:
arr.dtype

dtype('float64')

In [40]:
arr.astype(int)

array([1, 2, 3])

In [ ]:
#indexing & slicing

In [76]:
arr1=np.arange(10)
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr1[0]

np.int64(0)

In [79]:
arr1[9]

np.int64(9)

In [80]:
#18
arr1[2:6]

array([2, 3, 4, 5])

In [81]:
#19
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [82]:
#20
arr2[1,2]

np.int64(6)

In [83]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
#21
arr2[0,:]

array([1, 2, 3])

In [85]:
#22
arr2[:,1]

array([2, 5, 8])

In [86]:
#23
arr2[:2,:2]

array([[1, 2],
       [4, 5]])

In [91]:
#24 
a=arr1>5
a

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [92]:
#25
arr1[a]

array([6, 7, 8, 9])

In [93]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
#26
odd=arr2[arr2%2==1]
odd


array([1, 3, 5, 7, 9])

In [100]:
#27
replace=arr1[arr1>5]=0
replace

0

In [102]:
arr1

array([0, 1, 2, 3, 4, 5, 0, 0, 0, 0])

In [103]:
#28
arr1[[1,3,7]]

array([1, 3, 0])

In [104]:
#29
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
arr2[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [118]:
#30
arr1

array([0, 1, 2, 3, 4, 5, 0, 0, 0, 0])