In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,] # list
a

[1, 2, 3, 4]

In [4]:
arr=np.array([1,2,3,4]) #array
arr

array([1, 2, 3, 4])

In [5]:
arr= np.array([1,2,3.3,"rahul"])
arr

array(['1', '2', '3.3', 'rahul'], dtype='<U32')

In [6]:
l=[[1,2,3],[2,3,4],[5,6,7]]
l

[[1, 2, 3], [2, 3, 4], [5, 6, 7]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [8]:
#Create a 1D NumPy array from the Python list [1, 2, 3, 4, 5].
l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [9]:
#Create a 1D array of 10 zeros
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
#Create a 3x3 array filled with ones
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#Create an array of all even integers from 10 to 50.
arr=np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [18]:
#Create a 3x3 matrix with values ranging from 0 to 8
arr=np.arange(0,9,1)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
#Create a 4x4 identity matrix. 
arr=np.ones(16)
arr


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
mat=arr.reshape(4,4)
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
#second method
mat=np.eye(4)
mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#Create an array of 5 numbers evenly spaced between 0 and 1. 
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
#Create a 3x4 array filled with random numbers between 0 and 1
arr=np.random.rand(3,4)
arr

array([[0.58519189, 0.41676656, 0.42383632, 0.54637562],
       [0.19301037, 0.97645749, 0.93440119, 0.23334135],
       [0.71872007, 0.8084114 , 0.14800807, 0.97017573]])

In [34]:
#Create a 5x5 array with random integers from 1 to 100.
arr=np.random.randint(1,100,(5,5))
arr

array([[ 7, 61, 45, 91,  6],
       [47,  3, 33, 54, 70],
       [92, 74, 87,  6, 35],
       [46, 41, 42,  8, 31],
       [68, 21, 34, 56,  2]], dtype=int32)

In [36]:
#Given the array arr = np.arange(25).reshape(5, 5), find its shape. 
arr=np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
shape=arr.shape
shape

(5, 5)

In [40]:
 #For the same array arr, find its data type
datatype=arr.dtype
datatype

dtype('int64')

In [41]:
# For the same array arr, find the total number of elements.
number=arr.size
number

25

In [52]:
# Create the array [1, 2, 3] but make sure its data type is float.
arr=np.array([1,2,3],dtype=float)
arr

array([1., 2., 3.])

In [54]:
#Convert the data type of an existing integer array to float. 
type=arr.astype
type

<function ndarray.astype>

In [56]:
#SLICING 

arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [65]:
slic=arr[1:3,3:]
slic

array([[ 9, 10],
       [14, 15]])

In [68]:
arr=np.arange(1,10,1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
slice=arr[::-1]
slice

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
#Valid Sudoku

In [12]:
import numpy as np

In [22]:
arr = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [42]:
b = np.sum(arr,axis =1)
for i in b:
    if i !=45:
        print("sudoku is not valid")
        break
else:
    print("for rows it is valid")

for rows it is valid


In [43]:
b = np.sum(arr,axis =0)
for i in b:
    if i !=45:
        print("sudoku is not valid")
        break
else:
    print("for column it is valid")

for column it is valid


In [45]:
for i in range(0,9,3):
    for j in range (0,9,3):
        n=arr[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [112]:



import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [113]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [114]:
#Find the average age of students.
np.mean(data[:,0])


np.float64(18.4)

In [115]:
#Extract Math marks of all students.

maths=data[:,1]
maths

array([85, 92, 76, 65, 90])

In [116]:
#Find the highest Science mark.
science=np.max(data[:,2])
science


np.int64(95)

In [117]:
#Get details of the student who scored more than 90 in Math

data[data[:,1]>90]

array([[19, 92, 88]])

In [118]:
#Increase Math marks of all students by 5.
data[:,1]+5



array([90, 97, 81, 70, 95])

In [119]:
#Find how many students are younger than 19.
data[data[:,0]<19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [120]:
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [121]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:3] ,axis=0)

array([81.6, 83.2])

In [122]:
#Get data of students who scored at least 80 in both subjects
data[(data[:,1] >=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [132]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75] =0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

In [ ]:
asf